POST http://127.0.0.1:8000/api/payment-callback
Content-Type: application/json
Accept: application/json

{
  "va_numbers": [
    {
      "va_number": "00246435102",
      "bank": "bca"
    }
  ],
  "transaction_time": "2024-03-17 15:41:02",
  "transaction_status": "settlement",
  "transaction_id": "61c21463-2e36-4c59-8064-8a9e74b6572b",
  "status_message": "midtrans payment notification",
  "status_code": "200",
  "signature_key": "8833a1b338614ea18ba9f8d863900c07cefa9a3de368ae3cb2508d55749e0e911857b85626fd4e3aade44d056a61c4c0540ab271fed6877816cd9344ed5888a2",
  "settlement_time": "2024-03-17 16:41:40",
  "payment_type": "bank_transfer",
  "payment_amounts": [

  ],
  "order_id": "785762024031726017",
  "merchant_id": "G289300246",
  "gross_amount": "200000.00",
  "fraud_status": "accept",
  "expiry_time": "2024-03-18 15:41:01",
  "currency": "IDR"
}